/*
combine topo_s.cpu_ids into single file for each **timestep**.
The number id in output files is **timestep**.

Assume density is 4400!

argv list:
1st: prefix of CitcomSVE: the x in 'x.coord_s.y'
2nd: header file generated by A0_timestep_and_time.c
3rd: output files prefix
4th: nproc of surface
5th: nprocz
6th: nox (=noy)
*/

#include <math.h>
#include <stdio.h>
#include <fcntl.h>
#include <string.h>
#include <sys/types.h>
#include <stdlib.h>

int main(int argc, char **argv)
{
  if(argc != 7) {
    fprintf(stderr, "Usage: %s prefix_of_CitcomSVE header_file output_files_prefix nproc nprocz nox(=noy)\n", argv[0]);
    exit(1);
  }

  char filename[250],outputfile[250],inputfile[250],input_s[500];
  FILE *fp0,*fp1,*fp2,*fp3 ;
  float rad1, temp1,temp2;
  float scale_length,scale_potential;

  int nproc,i,ip,ipp,j,compute_node,nno,nox,noy;

  scale_length = 6371000;
  scale_potential = 4.0*M_PI*6.6742e-11*4400*scale_length*scale_length;
  
  printf("Scaling factors: Density = 4400, Length = 6371 km \n");
 
  nproc = atoi(argv[4]);    // number of the processes for the surface
  int nprocz = atoi(argv[5]);
  nox = noy = atoi(argv[6]); 
  nno = nox*noy;
  
  // nstep=atoi(argv[2]);

  /* Read timestep from header file */ 

  FILE * fp_header;
  char header_file[250];
  sprintf(header_file, "%s", argv[2]);
  fp_header = fopen(header_file, "r"); 
  if(fp_header == NULL) { fprintf(stderr, "Error: cannot open file %s\n", header_file); exit(1); }

  char line[250];

  fgets(line, 250, fp_header); // header description

  /*
  read each line, until the end of the file.
  The first number is the timestep.
  */
  int timestep;
  float time, time_incr;
  FILE * fp4, * fp5;
  float u, u_incr, phi, phi_incr, south, south_incr, east, east_incr;

  rad1 = 180.0 / M_PI;

  while(fgets(line, 250, fp_header) != NULL){
    sscanf(line, "%d %f %f", &timestep, &time, &time_incr);
    printf("Processing timestep %d, time %f, delta %f\n", timestep, time, time_incr);
    
    sprintf(filename,"%s.map_disp_and_geoid.%d",argv[3],timestep);  // timestep as suffix
    fp2=fopen(filename,"w");
    sprintf(filename,"%s.map_rate_disp_and_geoid.%d",argv[3],timestep);
    fp3=fopen(filename,"w");


    for (ipp = 1; ipp <= nproc; ipp++) {  // loop over the processes on the surface (ip)
      ip = nprocz * ipp - 1;
      sprintf(filename, "%s.coord_s.%d", argv[1], ip);
      fp0 = fopen(filename, "r");   if (fp0 == NULL) { fprintf(stderr, "Error: cannot open file %s\n", filename); exit(1); }
      fgets(input_s, 500, fp0);


      sprintf(filename, "%s.topo_s.%d.%d", argv[1], ip, timestep);
      fp1 = fopen(filename, "r");   if (fp1 == NULL) { fprintf(stderr, "Error: cannot open file %s\n", filename); exit(1); }
      fgets(input_s, 500, fp1); // header descp
      fgets(input_s, 500, fp1); // header numbers

      for (i = 1; i <= nno; i++) {
        fgets(input_s, 500, fp0);  // fp0: coord_s
        sscanf(input_s, "%f %f", &temp1, &temp2);

        fgets(input_s, 500, fp1);  // fp1: topo_s.cpu_id.timestep
        sscanf(input_s, "%f %f %f %f %f %f %f %f", &u, &u_incr, &phi, &phi_incr, &south, &south_incr, &east, &east_incr);

        
        temp1 = 90 - temp1 * rad1;
        temp2 = temp2 * rad1;

        u = u * scale_length;           // turn to meters
        phi = phi * scale_potential / 9.82;   
        south = south * scale_length;             
        east = east * scale_length;             
        u_incr = u_incr * scale_length / time_incr;           // turn to meters/year
        phi_incr = phi_incr * scale_potential / 9.82 / time_incr;
        south_incr = south_incr * scale_length / time_incr;
        east_incr = east_incr * scale_length / time_incr;

        fprintf(fp2, "%g %g %g %g %g %g\n", temp2, temp1, u, south, east, phi);
        fprintf(fp3, "%g %g %g %g %g %g\n", temp2, temp1, u_incr, south_incr, east_incr, phi_incr);

      }
      fclose(fp0);
      fclose(fp1);
    }

    fclose(fp2);
    fclose(fp3);
  }

  
  return 0;
 }
