/*
Get RSL_c from header of .topo_s.xx file.

Input parameters:
                1) stage2timestep file generated by A1_epoch_to_timestep
                2) prefix of the (path/case_id.topo_s.cpuid).timestep file. 
                3) the position of RSL_c in the header (starting from 0).
                4) the filename to write the output.

e.g.:
ice6g_122ka_stages_timeB.epoch_to_timestep.txt ../link_scratch_BM_SLE/case_v1_t2.topo_s.1  8   case_v1_t2.RSL_c
*/



#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int DEBUG = 1;

int main(int argc, char ** argv)
{
    char timedep_file[250], outputfile[250];
    char stage2timestep_file[250];
    int pos_RSL_c; // position of RSL_c in the header

    /* input parameters */
    sprintf(stage2timestep_file, "%s", argv[1]);
    sprintf(timedep_file, "%s", argv[2]);
    sscanf(argv[3], "%d", &pos_RSL_c);
    sprintf(outputfile, "%s", argv[4]);

    FILE * fp_timedep, *fp_stage2timestep, * fp_out;

    if((fp_stage2timestep = fopen(stage2timestep_file, "r")) == NULL)
    {
        printf("Error! opening file %s", stage2timestep_file);
        exit(1);
    }

    /*Read stage2timestep file*/ 

    int nstages;
    char line[250];
    char word[250];
    double RSL_c;
    int * stages2timestep;
    fgets(line, 250, fp_stage2timestep);
    sscanf(line, "%d", &nstages);
    stages2timestep = (int *) malloc(nstages * sizeof(int));
    int temp_int;
    for(int i = 0; i < nstages; i++)
    {
        fgets(line, 250, fp_stage2timestep);
        sscanf(line, "%d %d", &temp_int , &stages2timestep[i]);
        if(DEBUG)
            printf("%d %d\n", temp_int, stages2timestep[i]);
    }


    
    if((fp_out = fopen(outputfile, "w")) == NULL)
    {
        printf("Error! opening file %s", outputfile);
        exit(1);
    }

    fprintf(fp_out, "%d\n", nstages);  // write nstages to output file as first line    
    fprintf(fp_out, "0 %d 0.0\n", stages2timestep[0]); // write 0 for the first epoch (as it is not in the topo file)


    /*read time_dep file */


    if((fp_timedep = fopen(timedep_file, "r")) == NULL)
    {
        printf("Error! opening file %s", timedep_file);
        exit(1);
    }

    fgets(line, 250, fp_timedep); // skip first row

    for (int epoch=1; epoch<nstages; epoch++){
        
        do {
            fgets(line, 250, fp_timedep);
            sscanf(line, "%d", &temp_int);
        } while (temp_int != stages2timestep[epoch]); // find the line with the same epoch number

        printf("found epoch %d in line %s\n", temp_int, line);

        // now we are at the line with the same epoch number, and we already the first number

        // for(int i = 0; i <= pos_RSL_c; i++)
        // {
        //     // fscanf(fp_timedep, "%s", line);  // line here is not "line", but word (space separated)
        //     sscanf(line, "%s", word);
        // }

        // read the pos_RSL_c-th word from line
        char *token = strtok(line, " \t\n");
        int count = 0;
        while (token != NULL) {
            sscanf(token, "%lf", &RSL_c);
            token = strtok(NULL, " \t\n");
            count++;
            if (count == pos_RSL_c) {
                break;
            }
        }


        fprintf(fp_out, "%d %d %e\n", epoch, stages2timestep[epoch], RSL_c);

        if(DEBUG)
            printf("%d %d %e\n", epoch, stages2timestep[epoch], RSL_c);

    }
    
    fclose(fp_timedep);
    fclose(fp_stage2timestep);
    fclose(fp_out);
    
    return 0;
}