/*
Get RSL_c from header of .topo_s.xx file.

Input parameters:
                1) stage2timestep file generated by A1_epoch_to_timestep
                2) prefix of the (path/case_id.topo_s.cpuid).timestep file. 
                3) the position of RSL_c in the header (starting from 0).
                4) the filename to write the output.

e.g.:
ice6g_122ka_stages_timeB.epoch_to_timestep.txt ../link_scratch_BM_SLE/case_v1_t2.topo_s.1  8   case_v1_t2.RSL_c
*/



#include <stdio.h>
#include <stdlib.h>

int DEBUG = 0;

int main(int argc, char ** argv)
{
    char topo_prefix[250], outputfile[250];
    char stage2timestep_file[250];
    int pos_RSL_c; // position of RSL_c in the header

    /* input parameters */
    sprintf(stage2timestep_file, "%s", argv[1]);
    sprintf(topo_prefix, "%s", argv[2]);
    sscanf(argv[3], "%d", &pos_RSL_c);
    sprintf(outputfile, "%s", argv[4]);

    FILE * fp_topo, *fp_stage2timestep, * fp_out;

    if((fp_stage2timestep = fopen(stage2timestep_file, "r")) == NULL)
    {
        printf("Error! opening file %s", stage2timestep_file);
        exit(1);
    }

    /*Read stage2timestep file*/ 

    int nstages;
    char line[250];
    int * stages2timestep;
    fgets(line, 250, fp_stage2timestep);
    sscanf(line, "%d", &nstages);
    stages2timestep = (int *) malloc(nstages * sizeof(int));
    int temp_int;
    for(int i = 0; i < nstages; i++)
    {
        fgets(line, 250, fp_stage2timestep);
        sscanf(line, "%d %d", &temp_int , &stages2timestep[i]);
        if(DEBUG)
            printf("%d %d\n", temp_int, stages2timestep[i]);
    }


    
    if((fp_out = fopen(outputfile, "w")) == NULL)
    {
        printf("Error! opening file %s", outputfile);
        exit(1);
    }

    fprintf(fp_out, "%d\n", nstages);  // write nstages to output file as first line    
    fprintf(fp_out, "0 %d 0.0\n", stages2timestep[0]); // write 0 for the first epoch (as it is not in the topo file)


    /*read header of topo file */

    char topo_file[250];

    for (int epoch=1; epoch<nstages; epoch++){
        sprintf(topo_file, "%s.%d", topo_prefix, stages2timestep[epoch]);
        if((fp_topo = fopen(topo_file, "r")) == NULL)
        {
            printf("Error! opening file %s", topo_file);
            exit(1);
        }

        fgets(line, 250, fp_topo); // skip first row

        for(int i = 0; i <= pos_RSL_c; i++)
        {
            fscanf(fp_topo, "%s", line);  // line here is not "line", but word (space separated)
        }
        fprintf(fp_out, "%d %d %s\n", epoch, stages2timestep[epoch], line);

        if(DEBUG)
            printf("%d %d %s\n", epoch, stages2timestep[epoch], line);

        fclose(fp_topo);
    }


    fclose(fp_stage2timestep);
    fclose(fp_out);
    
    return 0;
}