/*
combine topo_s.cpu_is into single file for each **epoch**.
Need to know the timestep for each epoch (from stage2timestep file)
The number id in output files is **epoch**, not timestep.

Assume density is 4400!

argv list:
1st: prefix of CitcomSVE: the x in 'x.coord_s.y'
2nd: stage2timestep file generated by A1_epoch_to_timestep
3rd: output files prefix
4th: nproc of surface
5th: nprocz
6th: nox (=noy)
*/

#include <math.h>
#include <stdio.h>
#include <fcntl.h>
#include <string.h>
#include <sys/types.h>
#include <stdlib.h>

int main(int argc, char **argv)
{
  char filename[250],outputfile[250],inputfile[250],input_s[500];
  FILE *fp0,*fp1,*fp2,*fp3 ;
  float rad1, temp1,temp2,temp3,temp4,temp5,temp6;
  float scale_length,scale_potential;

  int nproc,i,ip,ipp,j,nstep,compute_node,nno,nox,noy;

  scale_length = 6371000;
  scale_potential = 4.0*M_PI*6.6742e-11*4400*scale_length*scale_length;
  
  printf("Scaling factors: Density = 4400, Length = 6371 km");
 
  nproc = atoi(argv[4]);    // number of the processes for the surface
  int nprocz = atoi(argv[5]);
  nox = noy = atoi(argv[6]); 
  nno = nox*noy;
  
  // nstep=atoi(argv[2]);

  /* Read stage2timestep file */ 

  FILE * fp_stage2timestep;
  char stage2timestep_file[250];
  sprintf(stage2timestep_file, "%s", argv[2]);
  fp_stage2timestep = fopen(stage2timestep_file, "r"); if(fp_stage2timestep == NULL) { fprintf(stderr, "Error: cannot open file %s\n", stage2timestep_file); exit(1); }

  int nstages;
  char line[250];
  int * stages2timestep;
  fgets(line, 250, fp_stage2timestep);
  sscanf(line, "%d", &nstages);
  stages2timestep = (int *) malloc(nstages * sizeof(int));
  int temp_int;
  for(int i = 0; i < nstages; i++)
  {
      fgets(line, 250, fp_stage2timestep);
      sscanf(line, "%d %d", &temp_int , &stages2timestep[i]);
  }

  /* 
    process each stage (nstep) 
  */

  rad1 = 180.0 / M_PI;

  for(int stage=0; stage<nstages; stage++)
  {
    nstep = stages2timestep[stage];

    printf("Processing stage %d, timestep %d\n", stage, nstep);
    
    sprintf(filename,"%s.map_uplift.epoch%d",argv[3],stage);  // use stage, instead of nstep
    fp2=fopen(filename,"w");
    sprintf(filename,"%s.map_geoid.epoch%d",argv[3],stage);
    fp3=fopen(filename,"w");

    for (ipp = 1; ipp <= nproc; ipp++) {  // loop over the processes on the surface (ip)
      ip = nprocz * ipp - 1;
      sprintf(filename, "%s.coord_s.%d", argv[1], ip);
      fp0 = fopen(filename, "r");   if (fp0 == NULL) { fprintf(stderr, "Error: cannot open file %s\n", filename); exit(1); }
      fgets(input_s, 500, fp0);

      if(stage != 0){  // no file for the first epoch
        sprintf(filename, "%s.topo_s.%d.%d", argv[1], ip, nstep);
        fp1 = fopen(filename, "r");   if (fp1 == NULL) { fprintf(stderr, "Error: cannot open file %s\n", filename); exit(1); }
        fgets(input_s, 500, fp1); // header descp
        fgets(input_s, 500, fp1); // header numbers
      }


      for (i = 1; i <= nno; i++) {
        fgets(input_s, 500, fp0);
        sscanf(input_s, "%f %f", &temp1, &temp2);

        /* first epoch is all 0 */
        if(stage != 0){
          fgets(input_s, 500, fp1);
          sscanf(input_s, "%f %f %f %f", &temp3, &temp4, &temp5, &temp6);
        }
        else{
          temp3 = 0.0;
          temp5 = 0.0;
        }

        temp1 = 90 - temp1 * rad1;
        temp2 = temp2 * rad1;
        temp3 = temp3 * scale_length;           // turn to meters
        temp5 = temp5 * scale_potential / 9.82; // turn to meters
        fprintf(fp2, "%g %g %g\n", temp2, temp1, temp3);
        fprintf(fp3, "%g %g %g\n", temp2, temp1, temp5);
        //  fprintf(fp4,"%g %g %g\n",temp2,temp1,temp7);
        //  fprintf(fp5,"%g %g %g\n",temp2,temp1,temp9);
      }
      fclose(fp0);

      if(stage != 0)
        fclose(fp1);
    }

    fclose(fp2);
    fclose(fp3);
  }

  
  return 0;
 }
